import BootstrapClient from "@/components/BootstrapClient";
import { AuthProvider } from "@/contexts/Auth";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "@/styles.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          <main>
            {children}
          </main>
          <BootstrapClient />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
